---

- hosts: localhost
  connection: local
  tasks:
    - name: install brew packages
      homebrew: name='{{ item }}' state=present
      with_items:
        - coreutils
        - git
        - curl
        - wget
        - tmux
        - mc
        - ssh-copy-id
        - ctags
        - rbenv
        - ack
        - node
        - pwgen
        - pdf2htmlex
        - youtube-dl
        - icu4c
        - reattach-to-user-namespace
        - sqlite
        - nmap
        - yarn
        - erlang
        - elixir
        - neovim/neovim/neovim
        - python3
        - kubernetes-cli
        - kubernetes-helm
        - hiredis
        - p7zip
        - poppler
        - libxml2
        - ffmpeg
        - telnet
        - jmeter
        - imagemagick@6
        - v8@3.15
        - mas
        - postgresql
        - overmind
        - bitwarden-cli
        - fzf

    - name: cask packages are installed
      homebrew_cask: name='{{ item }}' state=present
      with_items:
        - tunnelblick
        - wkhtmltopdf
        - virtualbox
        - docker
        - kitematic
        - gpg-suite
        - google-cloud-sdk
        - minikube
        - flash-npapi
        - mysql-shell
        - wireshark
        - imageoptim
        - yandexdisk
        - chromedriver
        - google-chrome
        - sublime-text
        - sketchup
        - zoomus
        - iterm2
        - java8
        - skype
        - visual-studio-code
        - psequel
        - sourcetree
        - vagrant
        - signal
        - kubernetic

    # configs

    - name: set config list
      set_fact:
        list:
          - .bundle/config
          - .config/nvim/init.vim
          - .private
          - .ssh
          - .tmuxinator/code.yml
          - .ackrc
          - .aliases
          - .ansible.cfg
          - .bash_profile
          - .ctags
          - .editorconfig
          - .eslintrc
          - .gemrc
          - .gitconfig
          - .gitignore_global
          - .rubocop.yml
          - .sublime-keys
          - .sublime-packages
          - .sublime-settings
          - .tmux.conf
          - .vimrc
          - .pryrc

    - name: create config dirs
      file: path='~/{{ item | dirname }}' state=directory
      with_items: '{{ list }}'

    - name: create config links
      file:
        src: '{{ playbook_dir }}/assets/{{ item }}'
        dest: '~/{{ item }}'
        state: link
        force: yes
      with_items: '{{ list }}'

    # packages

    - name: pip packages are installed
      pip:
        name: '{{ item }}'
        state: present
        executable: pip3
        extra_args: --user
      with_items:
        - neovim
        - awscli
        - ansible-vault
        - jmespath

    - name: node packages are installed
      npm: name='{{ item }}' state=present global=yes
      with_items:
        - eslint
        - eslint-plugin-react
        - eslint-plugin-node
        - babel-eslint

    - name: get ruby versions
      shell: rbenv versions
      register: list_ruby_versions
      changed_when: false

    - name: install ruby
      shell: rbenv install 2.5.3
      when: '"2.5.3" not in list_ruby_versions.stdout'
      register: install_ruby

    - name: set ruby
      shell: rbenv global 2.5.3
      register: set_ruby
      when: install_ruby.changed

    - name: install ruby
      shell: rbenv rehash
      when: set_ruby.changed

    - name: rbenv gems are installed
      gem:
        name: '{{ item }}'
        state: present
        executable: /usr/local/var/rbenv/shims/gem
      with_items:
        - bundler
        - foreman
        - rubocop
        - rubycritic
        - brakeman
        - bundle-audit
        - tmuxinator
        - neovim

    # sublime

    - name: install sublime config
      file:
        src: '~/.sublime-settings'
        dest: '~/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings'
        state: link
        force: yes
      ignore_errors: yes

    - name: install sublime keys
      file:
        src: '~/.sublime-keys'
        dest: '~/Library/Application Support/Sublime Text 3/Packages/User/Default (OSX).sublime-keymap'
        state: link
        force: yes
      ignore_errors: yes

    - name: install sublime packages
      file:
        src: '~/.sublime-packages'
        dest: '~/Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings'
        state: link
        force: yes
      ignore_errors: yes
