---

- hosts: localhost
  connection: local
  tasks:
    - name: install brew packages
      homebrew: name='{{ item }}' state=present
      with_items:
        - coreutils
        - git
        - curl
        - wget
        - tmux
        - mc
        - ssh-copy-id
        - ctags
        - rbenv
        - ack
        - node
        - pwgen
        - pdf2htmlex
        - youtube-dl
        - icu4c
        - reattach-to-user-namespace
        - sqlite
        - nmap
        - yarn
        - erlang
        - elixir
        - neovim/neovim/neovim
        - python3
        - kubernetes-cli
        - hiredis
        - p7zip
        - poppler
        - libxml2
        - ffmpeg
        - telnet
        - jmeter
        - imagemagick@6
        - v8@3.15
        #- libpqxx@3
        - mas
        #- https://raw.githubusercontent.com/turforlag/homebrew-cervezas/master/pdftk.rb

    - name: cask packages are installed
      homebrew_cask: name='{{ item }}' state=present
      with_items:
        - tunnelblick
        - wkhtmltopdf
        - virtualbox
        - docker
        - kitematic
        - gpg-suite
        - google-cloud-sdk
        - minikube
        - java8
        - flash-npapi
        - mysql-shell
        - wireshark
        - imageoptim
        - yandexdisk
        - chromedriver
        - google-chrome
        - sublime-text
        - paragon-ntfs
        - sketchup

    # configs

    - name: mac settings are changed
      command: 'defaults write {{ item }}'
      with_items:
        - 'NSGlobalDomain ApplePressAndHoldEnabled 0'
        - 'com.apple.systempreferences TMShowUnsupportedNetworkVolumes 1'
        - 'com.apple.desktopservices DSDontWriteNetworkStores 1'
        - 'com.apple.TextEdit RichText 0'
      changed_when: false

    - name: set config list
      set_fact:
        list:
          - .bundle/config
          - .config/nvim/init.vim
          - .private
          - .ssh
          - .tmuxinator/code.yml
          - .ackrc
          - .aliases
          - .ansible.cfg
          - .bash_profile
          - .ctags
          - .editorconfig
          - .eslintrc
          - .gemrc
          - .gitconfig
          - .gitignore_global
          - .rubocop.yml
          - .sublime-keys
          - .sublime-packages
          - .sublime-settings
          - .tmux.conf
          - .vimrc
          - .pryrc

    - name: create config dirs
      file: path='~/{{ item | dirname }}' state=directory
      with_items: '{{ list }}'

    - name: create config links
      file:
        src: '{{ playbook_dir }}/assets/{{ item }}'
        dest: '~/{{ item }}'
        state: link
        force: yes
      with_items: '{{ list }}'

    # packages

    - name: pip packages are installed
      pip:
        name: '{{ item }}'
        state: present
        executable: pip3
        extra_args: --user
      with_items:
        - neovim
        - awscli
        - ansible-vault
        - jmespath

    - name: node packages are installed
      npm: name='{{ item }}' state=present global=yes
      with_items:
        - eslint
        - eslint-plugin-react
        - eslint-plugin-node
        - babel-eslint

    - name: get ruby versions
      shell: rbenv versions
      register: rbenv_versions

    - name: install ruby
      shell: rbenv install 2.5.3
      when: '"2.5.3" not in rbenv_versions.stdout'

    - name: set ruby
      shell: rbenv global 2.5.3

    - name: install ruby
      shell: rbenv rehash

    - name: rbenv gems are installed
      gem:
        name: '{{ item }}'
        state: present
        executable: /usr/local/var/rbenv/shims/gem
      with_items:
        - bundler
        - foreman
        - rubocop
        - rubycritic
        - brakeman
        - bundle-audit
        - tmuxinator
        - neovim

    # sublime

    - name: create sublime symlink
      file:
        src: '/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl'
        dest: '/usr/local/bin/sublime'
        state: link
      ignore_errors: yes

    - name: install sublime config
      file:
        src: '~/.sublime-settings'
        dest: '~/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings'
        state: link
        force: yes
      ignore_errors: yes

    - name: install sublime keys
      file:
        src: '~/.sublime-keys'
        dest: '~/Library/Application Support/Sublime Text 3/Packages/User/Default (OSX).sublime-keymap'
        state: link
        force: yes
      ignore_errors: yes

    - name: install sublime packages
      file:
        src: '~/.sublime-packages'
        dest: '~/Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings'
        state: link
        force: yes
      ignore_errors: yes
