---

- hosts: localhost
  connection: local
  tasks:
    - name: set config list
      set_fact:
        list:
          - .bundle/config
          - .config/nvim/init.vim
          - .private
          - .ssh
          - .tmuxinator
          - .ackrc
          - .aliases
          - .ansible.cfg
          - .ctags
          - .editorconfig
          - .eslintrc
          - .gemrc
          - .gitconfig
          - .gitignore_global
          - .rubocop.yml
          - .sublime-keys
          - .sublime-packages
          - .sublime-settings
          - .tmux.conf
          - .vimrc
          - .pryrc
          - .zshrc

    - name: create config dirs
      file: path='~/{{ item | dirname }}' state=directory
      with_items: '{{ list }}'

    - name: create config links
      file:
        src: '{{ playbook_dir }}/assets/{{ item }}'
        dest: '~/{{ item }}'
        state: link
        force: yes
      with_items: '{{ list }}'

    # packages

    - name: pip packages are installed
      pip:
        name: '{{ item }}'
        state: present
        executable: pip3
        extra_args: --user
      with_items:
        - neovim
        - awscli
        - ansible-vault
        - jmespath

    # sublime

    - name: install sublime config
      file:
        src: '~/.sublime-settings'
        dest: '~/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings'
        state: link
        force: yes
      ignore_errors: yes

    - name: install sublime keys
      file:
        src: '~/.sublime-keys'
        dest: '~/Library/Application Support/Sublime Text 3/Packages/User/Default (OSX).sublime-keymap'
        state: link
        force: yes
      ignore_errors: yes

    - name: install sublime packages
      file:
        src: '~/.sublime-packages'
        dest: '~/Library/Application Support/Sublime Text 3/Packages/User/Package Control.sublime-settings'
        state: link
        force: yes
      ignore_errors: yes
